version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true