pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: VM
                      spec:
                          type: Pool
                          spec:
                              identifier: ubuntu
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    command: |-
                                        wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
                                        sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
                                        sudo apt update -y
                                        sudo apt install adoptopenjdk-8-hotspot -y
                                name: JDK
                                identifier: JDK
                  cloneCodebase: true
              name: linux
              identifier: linux
    properties:
        ci:
            codebase:
                repoName: spring-boot-admin
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Springboot_Admin2
    orgIdentifier: default
    name: build
    identifier: build
    allowStageExecutions: false
