pipeline:
    name: builds
    identifier: builds
    allowStageExecutions: false
    projectIdentifier: Springboot_Admin2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.Github
                repoName: spring-boot-admin
                build: <+input>
    stages:
        - parallel:
              - stage:
                    name: windows
                    identifier: linux
                    type: CI
                    spec:
                        cloneCodebase: true
                        infrastructure:
                            type: VM
                            spec:
                                type: Pool
                                spec:
                                    identifier: windows
                        execution:
                            steps:
                                - step:
                                      type: Run
                                      name: Build
                                      identifier: SetUp_Maven
                                      spec:
                                          command: |-
                                              choco install openjdk
                                              choco install maven
                                              refreshenv
                                              $Env:Path
                                              mvn -version
                                              mvn -B spring-javaformat:apply --no-transfer-progress
                                          shell: Powershell
                                - step:
                                      type: RunTests
                                      name: Run Tests
                                      identifier: Tests
                                      spec:
                                          language: Java
                                          buildTool: Maven
                                          args: -B verify -P coverage --no-transfer-progress -D maven.javadoc.skip=true
                                          runOnlySelectedTests: true
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                          shell: Powershell
              - stage:
                    name: linux
                    identifier: linux1
                    type: CI
                    spec:
                        cloneCodebase: true
                        infrastructure:
                            type: KubernetesDirect
                            spec:
                                connectorRef: org.GKE
                                namespace: harness-delegate-ng
                        execution:
                            steps:
                                - step:
                                      type: Run
                                      name: Build
                                      identifier: Build
                                      spec:
                                          connectorRef: org.Dockerhub
                                          image: maven:3.8.4-openjdk-8
                                          command: mvn -B spring-javaformat:apply --no-transfer-progress
                                - step:
                                      type: RunTests
                                      name: Run Tests
                                      identifier: Run_Tests
                                      spec:
                                          connectorRef: org.Dockerhub
                                          image: maven:3.8.4-openjdk-8
                                          language: Java
                                          buildTool: Maven
                                          args: -B verify -P coverage --no-transfer-progress -D maven.javadoc.skip=true
                                          runOnlySelectedTests: true
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                          resources:
                                              limits:
                                                  memory: 1Gi
                                                  cpu: "1.0"
