pipeline:
    name: VMbuild
    identifier: VMbuild
    allowStageExecutions: false
    projectIdentifier: Springboot_Admin2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.Github
                repoName: spring-boot-admin
                build: <+input>
    stages:
        - stage:
              name: windows
              identifier: linux
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: VM
                      spec:
                          type: Pool
                          spec:
                              identifier: windows
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Run
                                      name: SetUp JDK
                                      identifier: SetUp_JDK
                                      spec:
                                          command: choco install openjdk
                                          shell: Powershell
                                - step:
                                      type: Run
                                      name: SetUp Maven
                                      identifier: SetUp_Maven
                                      spec:
                                          command: choco install maven
                                          shell: Powershell
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    command: $Env:Path
                                    shell: Powershell
